# permissions for end users to edit keaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ocp-kea-dhcp
    app.kubernetes.io/managed-by: kustomize
  name: keaserver-editor-role
rules:
- apiGroups:
  - kea.openshift.io
  resources:
  - keaservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kea.openshift.io
  resources:
  - keaservers/status
  verbs:
  - get
