//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentControlSockets) DeepCopyInto(out *AgentControlSockets) {
	*out = *in
	if in.Dhcp4 != nil {
		in, out := &in.Dhcp4, &out.Dhcp4
		*out = new(ControlSocket)
		(*in).DeepCopyInto(*out)
	}
	if in.Dhcp6 != nil {
		in, out := &in.Dhcp6, &out.Dhcp6
		*out = new(ControlSocket)
		(*in).DeepCopyInto(*out)
	}
	if in.D2 != nil {
		in, out := &in.D2, &out.D2
		*out = new(ControlSocket)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentControlSockets.
func (in *AgentControlSockets) DeepCopy() *AgentControlSockets {
	if in == nil {
		return nil
	}
	out := new(AgentControlSockets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthClient) DeepCopyInto(out *AuthClient) {
	*out = *in
	if in.PasswordSecretKeyRef != nil {
		in, out := &in.PasswordSecretKeyRef, &out.PasswordSecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthClient.
func (in *AuthClient) DeepCopy() *AuthClient {
	if in == nil {
		return nil
	}
	out := new(AuthClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]AuthClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientClass) DeepCopyInto(out *ClientClass) {
	*out = *in
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OnlyIfRequired != nil {
		in, out := &in.OnlyIfRequired, &out.OnlyIfRequired
		*out = new(bool)
		**out = **in
	}
	if in.ValidLifetime != nil {
		in, out := &in.ValidLifetime, &out.ValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MinValidLifetime != nil {
		in, out := &in.MinValidLifetime, &out.MinValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MaxValidLifetime != nil {
		in, out := &in.MaxValidLifetime, &out.MaxValidLifetime
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientClass.
func (in *ClientClass) DeepCopy() *ClientClass {
	if in == nil {
		return nil
	}
	out := new(ClientClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionStatus) DeepCopyInto(out *ConditionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionStatus.
func (in *ConditionStatus) DeepCopy() *ConditionStatus {
	if in == nil {
		return nil
	}
	out := new(ConditionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfig) DeepCopyInto(out *ContainerConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfig.
func (in *ContainerConfig) DeepCopy() *ContainerConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlSocket) DeepCopyInto(out *ControlSocket) {
	*out = *in
	if in.SocketPort != nil {
		in, out := &in.SocketPort, &out.SocketPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlSocket.
func (in *ControlSocket) DeepCopy() *ControlSocket {
	if in == nil {
		return nil
	}
	out := new(ControlSocket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DDNSConfig) DeepCopyInto(out *DDNSConfig) {
	*out = *in
	if in.DDNSDomains != nil {
		in, out := &in.DDNSDomains, &out.DDNSDomains
		*out = make([]DDNSDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DDNSConfig.
func (in *DDNSConfig) DeepCopy() *DDNSConfig {
	if in == nil {
		return nil
	}
	out := new(DDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DDNSDomain) DeepCopyInto(out *DDNSDomain) {
	*out = *in
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = make([]DNSServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DDNSDomain.
func (in *DDNSDomain) DeepCopy() *DDNSDomain {
	if in == nil {
		return nil
	}
	out := new(DDNSDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSServer) DeepCopyInto(out *DNSServer) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSServer.
func (in *DNSServer) DeepCopy() *DNSServer {
	if in == nil {
		return nil
	}
	out := new(DNSServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.Persist != nil {
		in, out := &in.Persist, &out.Persist
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(int32)
		**out = **in
	}
	if in.MaxReconnectTries != nil {
		in, out := &in.MaxReconnectTries, &out.MaxReconnectTries
		*out = new(int32)
		**out = **in
	}
	if in.ReconnectWaitTime != nil {
		in, out := &in.ReconnectWaitTime, &out.ReconnectWaitTime
		*out = new(int32)
		**out = **in
	}
	if in.RetryOnStartup != nil {
		in, out := &in.RetryOnStartup, &out.RetryOnStartup
		*out = new(bool)
		**out = **in
	}
	if in.LFCInterval != nil {
		in, out := &in.LFCInterval, &out.LFCInterval
		*out = new(int32)
		**out = **in
	}
	if in.MaxRowErrors != nil {
		in, out := &in.MaxRowErrors, &out.MaxRowErrors
		*out = new(int32)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(int32)
		**out = **in
	}
	if in.WriteTimeout != nil {
		in, out := &in.WriteTimeout, &out.WriteTimeout
		*out = new(int32)
		**out = **in
	}
	if in.TCPUserTimeout != nil {
		in, out := &in.TCPUserTimeout, &out.TCPUserTimeout
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAConfig) DeepCopyInto(out *HAConfig) {
	*out = *in
	if in.HeartbeatDelay != nil {
		in, out := &in.HeartbeatDelay, &out.HeartbeatDelay
		*out = new(int32)
		**out = **in
	}
	if in.MaxResponseDelay != nil {
		in, out := &in.MaxResponseDelay, &out.MaxResponseDelay
		*out = new(int32)
		**out = **in
	}
	if in.MaxAckDelay != nil {
		in, out := &in.MaxAckDelay, &out.MaxAckDelay
		*out = new(int32)
		**out = **in
	}
	if in.MaxUnackedClients != nil {
		in, out := &in.MaxUnackedClients, &out.MaxUnackedClients
		*out = new(int32)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]HAPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SendLeaseUpdates != nil {
		in, out := &in.SendLeaseUpdates, &out.SendLeaseUpdates
		*out = new(bool)
		**out = **in
	}
	if in.SyncLeases != nil {
		in, out := &in.SyncLeases, &out.SyncLeases
		*out = new(bool)
		**out = **in
	}
	if in.SyncTimeout != nil {
		in, out := &in.SyncTimeout, &out.SyncTimeout
		*out = new(int32)
		**out = **in
	}
	if in.SyncPageLimit != nil {
		in, out := &in.SyncPageLimit, &out.SyncPageLimit
		*out = new(int32)
		**out = **in
	}
	if in.DelayedUpdatesLimit != nil {
		in, out := &in.DelayedUpdatesLimit, &out.DelayedUpdatesLimit
		*out = new(int32)
		**out = **in
	}
	if in.MultiThreading != nil {
		in, out := &in.MultiThreading, &out.MultiThreading
		*out = new(HAMultiThreading)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAConfig.
func (in *HAConfig) DeepCopy() *HAConfig {
	if in == nil {
		return nil
	}
	out := new(HAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAMultiThreading) DeepCopyInto(out *HAMultiThreading) {
	*out = *in
	if in.EnableMultiThreading != nil {
		in, out := &in.EnableMultiThreading, &out.EnableMultiThreading
		*out = new(bool)
		**out = **in
	}
	if in.HTTPClientThreads != nil {
		in, out := &in.HTTPClientThreads, &out.HTTPClientThreads
		*out = new(int32)
		**out = **in
	}
	if in.HTTPListenerThreads != nil {
		in, out := &in.HTTPListenerThreads, &out.HTTPListenerThreads
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAMultiThreading.
func (in *HAMultiThreading) DeepCopy() *HAMultiThreading {
	if in == nil {
		return nil
	}
	out := new(HAMultiThreading)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAPeer) DeepCopyInto(out *HAPeer) {
	*out = *in
	if in.AutoFailover != nil {
		in, out := &in.AutoFailover, &out.AutoFailover
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAPeer.
func (in *HAPeer) DeepCopy() *HAPeer {
	if in == nil {
		return nil
	}
	out := new(HAPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookLibrary) DeepCopyInto(out *HookLibrary) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookLibrary.
func (in *HookLibrary) DeepCopy() *HookLibrary {
	if in == nil {
		return nil
	}
	out := new(HookLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfacesConfig) DeepCopyInto(out *InterfacesConfig) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReDetect != nil {
		in, out := &in.ReDetect, &out.ReDetect
		*out = new(bool)
		**out = **in
	}
	if in.ServiceSocketsRequireAll != nil {
		in, out := &in.ServiceSocketsRequireAll, &out.ServiceSocketsRequireAll
		*out = new(bool)
		**out = **in
	}
	if in.ServiceSocketsMaxRetries != nil {
		in, out := &in.ServiceSocketsMaxRetries, &out.ServiceSocketsMaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.ServiceSocketsRetryWaitTime != nil {
		in, out := &in.ServiceSocketsRetryWaitTime, &out.ServiceSocketsRetryWaitTime
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfacesConfig.
func (in *InterfacesConfig) DeepCopy() *InterfacesConfig {
	if in == nil {
		return nil
	}
	out := new(InterfacesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaControlAgent) DeepCopyInto(out *KeaControlAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaControlAgent.
func (in *KeaControlAgent) DeepCopy() *KeaControlAgent {
	if in == nil {
		return nil
	}
	out := new(KeaControlAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaControlAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaControlAgentList) DeepCopyInto(out *KeaControlAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeaControlAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaControlAgentList.
func (in *KeaControlAgentList) DeepCopy() *KeaControlAgentList {
	if in == nil {
		return nil
	}
	out := new(KeaControlAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaControlAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaControlAgentSpec) DeepCopyInto(out *KeaControlAgentSpec) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PodPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPPort != nil {
		in, out := &in.HTTPPort, &out.HTTPPort
		*out = new(int32)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlSockets != nil {
		in, out := &in.ControlSockets, &out.ControlSockets
		*out = new(AgentControlSockets)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HooksLibraries != nil {
		in, out := &in.HooksLibraries, &out.HooksLibraries
		*out = make([]HookLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make([]LoggerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaControlAgentSpec.
func (in *KeaControlAgentSpec) DeepCopy() *KeaControlAgentSpec {
	if in == nil {
		return nil
	}
	out := new(KeaControlAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaControlAgentStatus) DeepCopyInto(out *KeaControlAgentStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaControlAgentStatus.
func (in *KeaControlAgentStatus) DeepCopy() *KeaControlAgentStatus {
	if in == nil {
		return nil
	}
	out := new(KeaControlAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp4Server) DeepCopyInto(out *KeaDhcp4Server) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp4Server.
func (in *KeaDhcp4Server) DeepCopy() *KeaDhcp4Server {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp4Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaDhcp4Server) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp4ServerList) DeepCopyInto(out *KeaDhcp4ServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeaDhcp4Server, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp4ServerList.
func (in *KeaDhcp4ServerList) DeepCopy() *KeaDhcp4ServerList {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp4ServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaDhcp4ServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp4ServerSpec) DeepCopyInto(out *KeaDhcp4ServerSpec) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PodPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	in.InterfacesConfig.DeepCopyInto(&out.InterfacesConfig)
	if in.LeaseDatabase != nil {
		in, out := &in.LeaseDatabase, &out.LeaseDatabase
		*out = new(DatabaseConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HostsDatabase != nil {
		in, out := &in.HostsDatabase, &out.HostsDatabase
		*out = new(DatabaseConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HostsDatabases != nil {
		in, out := &in.HostsDatabases, &out.HostsDatabases
		*out = make([]DatabaseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subnet4 != nil {
		in, out := &in.Subnet4, &out.Subnet4
		*out = make([]Subnet4, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SharedNetworks != nil {
		in, out := &in.SharedNetworks, &out.SharedNetworks
		*out = make([]SharedNetwork4, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionDef != nil {
		in, out := &in.OptionDef, &out.OptionDef
		*out = make([]OptionDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientClasses != nil {
		in, out := &in.ClientClasses, &out.ClientClasses
		*out = make([]ClientClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make([]Reservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostReservationIdentifiers != nil {
		in, out := &in.HostReservationIdentifiers, &out.HostReservationIdentifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HooksLibraries != nil {
		in, out := &in.HooksLibraries, &out.HooksLibraries
		*out = make([]HookLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ControlSocket != nil {
		in, out := &in.ControlSocket, &out.ControlSocket
		*out = new(ControlSocket)
		(*in).DeepCopyInto(*out)
	}
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make([]LoggerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidLifetime != nil {
		in, out := &in.ValidLifetime, &out.ValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MinValidLifetime != nil {
		in, out := &in.MinValidLifetime, &out.MinValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MaxValidLifetime != nil {
		in, out := &in.MaxValidLifetime, &out.MaxValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.RenewTimer != nil {
		in, out := &in.RenewTimer, &out.RenewTimer
		*out = new(int32)
		**out = **in
	}
	if in.RebindTimer != nil {
		in, out := &in.RebindTimer, &out.RebindTimer
		*out = new(int32)
		**out = **in
	}
	if in.CalculateTeeTimes != nil {
		in, out := &in.CalculateTeeTimes, &out.CalculateTeeTimes
		*out = new(bool)
		**out = **in
	}
	if in.T1Percent != nil {
		in, out := &in.T1Percent, &out.T1Percent
		*out = new(string)
		**out = **in
	}
	if in.T2Percent != nil {
		in, out := &in.T2Percent, &out.T2Percent
		*out = new(string)
		**out = **in
	}
	if in.Authoritative != nil {
		in, out := &in.Authoritative, &out.Authoritative
		*out = new(bool)
		**out = **in
	}
	if in.MatchClientID != nil {
		in, out := &in.MatchClientID, &out.MatchClientID
		*out = new(bool)
		**out = **in
	}
	if in.DDNSSendUpdates != nil {
		in, out := &in.DDNSSendUpdates, &out.DDNSSendUpdates
		*out = new(bool)
		**out = **in
	}
	if in.DDNSOverrideNoUpdate != nil {
		in, out := &in.DDNSOverrideNoUpdate, &out.DDNSOverrideNoUpdate
		*out = new(bool)
		**out = **in
	}
	if in.DDNSOverrideClientUpdate != nil {
		in, out := &in.DDNSOverrideClientUpdate, &out.DDNSOverrideClientUpdate
		*out = new(bool)
		**out = **in
	}
	if in.DDNSUseConflictResolution != nil {
		in, out := &in.DDNSUseConflictResolution, &out.DDNSUseConflictResolution
		*out = new(bool)
		**out = **in
	}
	if in.HighAvailability != nil {
		in, out := &in.HighAvailability, &out.HighAvailability
		*out = new(HAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiThreading != nil {
		in, out := &in.MultiThreading, &out.MultiThreading
		*out = new(MultiThreadingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Stork != nil {
		in, out := &in.Stork, &out.Stork
		*out = new(StorkAgentConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp4ServerSpec.
func (in *KeaDhcp4ServerSpec) DeepCopy() *KeaDhcp4ServerSpec {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp4ServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp4ServerStatus) DeepCopyInto(out *KeaDhcp4ServerStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
	if in.NADAddresses != nil {
		in, out := &in.NADAddresses, &out.NADAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp4ServerStatus.
func (in *KeaDhcp4ServerStatus) DeepCopy() *KeaDhcp4ServerStatus {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp4ServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp6Server) DeepCopyInto(out *KeaDhcp6Server) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp6Server.
func (in *KeaDhcp6Server) DeepCopy() *KeaDhcp6Server {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp6Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaDhcp6Server) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp6ServerList) DeepCopyInto(out *KeaDhcp6ServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeaDhcp6Server, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp6ServerList.
func (in *KeaDhcp6ServerList) DeepCopy() *KeaDhcp6ServerList {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp6ServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaDhcp6ServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp6ServerSpec) DeepCopyInto(out *KeaDhcp6ServerSpec) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PodPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	in.InterfacesConfig.DeepCopyInto(&out.InterfacesConfig)
	if in.LeaseDatabase != nil {
		in, out := &in.LeaseDatabase, &out.LeaseDatabase
		*out = new(DatabaseConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HostsDatabase != nil {
		in, out := &in.HostsDatabase, &out.HostsDatabase
		*out = new(DatabaseConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HostsDatabases != nil {
		in, out := &in.HostsDatabases, &out.HostsDatabases
		*out = make([]DatabaseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subnet6 != nil {
		in, out := &in.Subnet6, &out.Subnet6
		*out = make([]Subnet6, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SharedNetworks != nil {
		in, out := &in.SharedNetworks, &out.SharedNetworks
		*out = make([]SharedNetwork6, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionDef != nil {
		in, out := &in.OptionDef, &out.OptionDef
		*out = make([]OptionDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientClasses != nil {
		in, out := &in.ClientClasses, &out.ClientClasses
		*out = make([]ClientClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make([]Reservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HostReservationIdentifiers != nil {
		in, out := &in.HostReservationIdentifiers, &out.HostReservationIdentifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HooksLibraries != nil {
		in, out := &in.HooksLibraries, &out.HooksLibraries
		*out = make([]HookLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ControlSocket != nil {
		in, out := &in.ControlSocket, &out.ControlSocket
		*out = new(ControlSocket)
		(*in).DeepCopyInto(*out)
	}
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make([]LoggerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreferredLifetime != nil {
		in, out := &in.PreferredLifetime, &out.PreferredLifetime
		*out = new(int32)
		**out = **in
	}
	if in.ValidLifetime != nil {
		in, out := &in.ValidLifetime, &out.ValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MinValidLifetime != nil {
		in, out := &in.MinValidLifetime, &out.MinValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MaxValidLifetime != nil {
		in, out := &in.MaxValidLifetime, &out.MaxValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.RenewTimer != nil {
		in, out := &in.RenewTimer, &out.RenewTimer
		*out = new(int32)
		**out = **in
	}
	if in.RebindTimer != nil {
		in, out := &in.RebindTimer, &out.RebindTimer
		*out = new(int32)
		**out = **in
	}
	if in.CalculateTeeTimes != nil {
		in, out := &in.CalculateTeeTimes, &out.CalculateTeeTimes
		*out = new(bool)
		**out = **in
	}
	if in.T1Percent != nil {
		in, out := &in.T1Percent, &out.T1Percent
		*out = new(string)
		**out = **in
	}
	if in.T2Percent != nil {
		in, out := &in.T2Percent, &out.T2Percent
		*out = new(string)
		**out = **in
	}
	if in.RapidCommit != nil {
		in, out := &in.RapidCommit, &out.RapidCommit
		*out = new(bool)
		**out = **in
	}
	if in.DDNSSendUpdates != nil {
		in, out := &in.DDNSSendUpdates, &out.DDNSSendUpdates
		*out = new(bool)
		**out = **in
	}
	if in.HighAvailability != nil {
		in, out := &in.HighAvailability, &out.HighAvailability
		*out = new(HAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiThreading != nil {
		in, out := &in.MultiThreading, &out.MultiThreading
		*out = new(MultiThreadingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Stork != nil {
		in, out := &in.Stork, &out.Stork
		*out = new(StorkAgentConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp6ServerSpec.
func (in *KeaDhcp6ServerSpec) DeepCopy() *KeaDhcp6ServerSpec {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp6ServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcp6ServerStatus) DeepCopyInto(out *KeaDhcp6ServerStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcp6ServerStatus.
func (in *KeaDhcp6ServerStatus) DeepCopy() *KeaDhcp6ServerStatus {
	if in == nil {
		return nil
	}
	out := new(KeaDhcp6ServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcpDdns) DeepCopyInto(out *KeaDhcpDdns) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcpDdns.
func (in *KeaDhcpDdns) DeepCopy() *KeaDhcpDdns {
	if in == nil {
		return nil
	}
	out := new(KeaDhcpDdns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaDhcpDdns) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcpDdnsList) DeepCopyInto(out *KeaDhcpDdnsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeaDhcpDdns, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcpDdnsList.
func (in *KeaDhcpDdnsList) DeepCopy() *KeaDhcpDdnsList {
	if in == nil {
		return nil
	}
	out := new(KeaDhcpDdnsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaDhcpDdnsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcpDdnsSpec) DeepCopyInto(out *KeaDhcpDdnsSpec) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PodPlacement)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.DNSServerTimeout != nil {
		in, out := &in.DNSServerTimeout, &out.DNSServerTimeout
		*out = new(int32)
		**out = **in
	}
	if in.TSIGKeys != nil {
		in, out := &in.TSIGKeys, &out.TSIGKeys
		*out = make([]TSIGKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ForwardDDNS != nil {
		in, out := &in.ForwardDDNS, &out.ForwardDDNS
		*out = new(DDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ReverseDDNS != nil {
		in, out := &in.ReverseDDNS, &out.ReverseDDNS
		*out = new(DDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlSocket != nil {
		in, out := &in.ControlSocket, &out.ControlSocket
		*out = new(ControlSocket)
		(*in).DeepCopyInto(*out)
	}
	if in.HooksLibraries != nil {
		in, out := &in.HooksLibraries, &out.HooksLibraries
		*out = make([]HookLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make([]LoggerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcpDdnsSpec.
func (in *KeaDhcpDdnsSpec) DeepCopy() *KeaDhcpDdnsSpec {
	if in == nil {
		return nil
	}
	out := new(KeaDhcpDdnsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaDhcpDdnsStatus) DeepCopyInto(out *KeaDhcpDdnsStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaDhcpDdnsStatus.
func (in *KeaDhcpDdnsStatus) DeepCopy() *KeaDhcpDdnsStatus {
	if in == nil {
		return nil
	}
	out := new(KeaDhcpDdnsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaServer) DeepCopyInto(out *KeaServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaServer.
func (in *KeaServer) DeepCopy() *KeaServer {
	if in == nil {
		return nil
	}
	out := new(KeaServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaServerList) DeepCopyInto(out *KeaServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeaServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaServerList.
func (in *KeaServerList) DeepCopy() *KeaServerList {
	if in == nil {
		return nil
	}
	out := new(KeaServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaServerSpec) DeepCopyInto(out *KeaServerSpec) {
	*out = *in
	if in.Dhcp4 != nil {
		in, out := &in.Dhcp4, &out.Dhcp4
		*out = new(KeaDhcp4ServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Dhcp6 != nil {
		in, out := &in.Dhcp6, &out.Dhcp6
		*out = new(KeaDhcp6ServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlAgent != nil {
		in, out := &in.ControlAgent, &out.ControlAgent
		*out = new(KeaControlAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DhcpDdns != nil {
		in, out := &in.DhcpDdns, &out.DhcpDdns
		*out = new(KeaDhcpDdnsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StorkServer != nil {
		in, out := &in.StorkServer, &out.StorkServer
		*out = new(KeaStorkServerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaServerSpec.
func (in *KeaServerSpec) DeepCopy() *KeaServerSpec {
	if in == nil {
		return nil
	}
	out := new(KeaServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaServerStatus) DeepCopyInto(out *KeaServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ConditionStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaServerStatus.
func (in *KeaServerStatus) DeepCopy() *KeaServerStatus {
	if in == nil {
		return nil
	}
	out := new(KeaServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaStorkServer) DeepCopyInto(out *KeaStorkServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaStorkServer.
func (in *KeaStorkServer) DeepCopy() *KeaStorkServer {
	if in == nil {
		return nil
	}
	out := new(KeaStorkServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaStorkServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaStorkServerList) DeepCopyInto(out *KeaStorkServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeaStorkServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaStorkServerList.
func (in *KeaStorkServerList) DeepCopy() *KeaStorkServerList {
	if in == nil {
		return nil
	}
	out := new(KeaStorkServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeaStorkServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaStorkServerSpec) DeepCopyInto(out *KeaStorkServerSpec) {
	*out = *in
	in.Container.DeepCopyInto(&out.Container)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Database.DeepCopyInto(&out.Database)
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.EnableMetrics != nil {
		in, out := &in.EnableMetrics, &out.EnableMetrics
		*out = new(bool)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PodPlacement)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaStorkServerSpec.
func (in *KeaStorkServerSpec) DeepCopy() *KeaStorkServerSpec {
	if in == nil {
		return nil
	}
	out := new(KeaStorkServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeaStorkServerStatus) DeepCopyInto(out *KeaStorkServerStatus) {
	*out = *in
	in.ComponentStatus.DeepCopyInto(&out.ComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeaStorkServerStatus.
func (in *KeaStorkServerStatus) DeepCopy() *KeaStorkServerStatus {
	if in == nil {
		return nil
	}
	out := new(KeaStorkServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogOutputOption) DeepCopyInto(out *LogOutputOption) {
	*out = *in
	if in.Maxsize != nil {
		in, out := &in.Maxsize, &out.Maxsize
		*out = new(int64)
		**out = **in
	}
	if in.Maxver != nil {
		in, out := &in.Maxver, &out.Maxver
		*out = new(int32)
		**out = **in
	}
	if in.Flush != nil {
		in, out := &in.Flush, &out.Flush
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogOutputOption.
func (in *LogOutputOption) DeepCopy() *LogOutputOption {
	if in == nil {
		return nil
	}
	out := new(LogOutputOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggerConfig) DeepCopyInto(out *LoggerConfig) {
	*out = *in
	if in.DebugLevel != nil {
		in, out := &in.DebugLevel, &out.DebugLevel
		*out = new(int32)
		**out = **in
	}
	if in.OutputOptions != nil {
		in, out := &in.OutputOptions, &out.OutputOptions
		*out = make([]LogOutputOption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggerConfig.
func (in *LoggerConfig) DeepCopy() *LoggerConfig {
	if in == nil {
		return nil
	}
	out := new(LoggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiThreadingConfig) DeepCopyInto(out *MultiThreadingConfig) {
	*out = *in
	if in.EnableMultiThreading != nil {
		in, out := &in.EnableMultiThreading, &out.EnableMultiThreading
		*out = new(bool)
		**out = **in
	}
	if in.ThreadPoolSize != nil {
		in, out := &in.ThreadPoolSize, &out.ThreadPoolSize
		*out = new(int32)
		**out = **in
	}
	if in.PacketQueueSize != nil {
		in, out := &in.PacketQueueSize, &out.PacketQueueSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiThreadingConfig.
func (in *MultiThreadingConfig) DeepCopy() *MultiThreadingConfig {
	if in == nil {
		return nil
	}
	out := new(MultiThreadingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionData) DeepCopyInto(out *OptionData) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(int32)
		**out = **in
	}
	if in.CSVFormat != nil {
		in, out := &in.CSVFormat, &out.CSVFormat
		*out = new(bool)
		**out = **in
	}
	if in.AlwaysSend != nil {
		in, out := &in.AlwaysSend, &out.AlwaysSend
		*out = new(bool)
		**out = **in
	}
	if in.NeverSend != nil {
		in, out := &in.NeverSend, &out.NeverSend
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionData.
func (in *OptionData) DeepCopy() *OptionData {
	if in == nil {
		return nil
	}
	out := new(OptionData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionDef) DeepCopyInto(out *OptionDef) {
	*out = *in
	if in.Array != nil {
		in, out := &in.Array, &out.Array
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionDef.
func (in *OptionDef) DeepCopy() *OptionDef {
	if in == nil {
		return nil
	}
	out := new(OptionDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDPool) DeepCopyInto(out *PDPool) {
	*out = *in
	if in.ExcludedPrefixLen != nil {
		in, out := &in.ExcludedPrefixLen, &out.ExcludedPrefixLen
		*out = new(int32)
		**out = **in
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDPool.
func (in *PDPool) DeepCopy() *PDPool {
	if in == nil {
		return nil
	}
	out := new(PDPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodPlacement) DeepCopyInto(out *PodPlacement) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodPlacement.
func (in *PodPlacement) DeepCopy() *PodPlacement {
	if in == nil {
		return nil
	}
	out := new(PodPlacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool4) DeepCopyInto(out *Pool4) {
	*out = *in
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequireClientClasses != nil {
		in, out := &in.RequireClientClasses, &out.RequireClientClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool4.
func (in *Pool4) DeepCopy() *Pool4 {
	if in == nil {
		return nil
	}
	out := new(Pool4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool6) DeepCopyInto(out *Pool6) {
	*out = *in
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequireClientClasses != nil {
		in, out := &in.RequireClientClasses, &out.RequireClientClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool6.
func (in *Pool6) DeepCopy() *Pool6 {
	if in == nil {
		return nil
	}
	out := new(Pool6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayInfo) DeepCopyInto(out *RelayInfo) {
	*out = *in
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayInfo.
func (in *RelayInfo) DeepCopy() *RelayInfo {
	if in == nil {
		return nil
	}
	out := new(RelayInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reservation) DeepCopyInto(out *Reservation) {
	*out = *in
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientClasses != nil {
		in, out := &in.ClientClasses, &out.ClientClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reservation.
func (in *Reservation) DeepCopy() *Reservation {
	if in == nil {
		return nil
	}
	out := new(Reservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedNetwork4) DeepCopyInto(out *SharedNetwork4) {
	*out = *in
	if in.Subnet4 != nil {
		in, out := &in.Subnet4, &out.Subnet4
		*out = make([]Subnet4, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Relay != nil {
		in, out := &in.Relay, &out.Relay
		*out = new(RelayInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.RequireClientClasses != nil {
		in, out := &in.RequireClientClasses, &out.RequireClientClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidLifetime != nil {
		in, out := &in.ValidLifetime, &out.ValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MinValidLifetime != nil {
		in, out := &in.MinValidLifetime, &out.MinValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MaxValidLifetime != nil {
		in, out := &in.MaxValidLifetime, &out.MaxValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.RenewTimer != nil {
		in, out := &in.RenewTimer, &out.RenewTimer
		*out = new(int32)
		**out = **in
	}
	if in.RebindTimer != nil {
		in, out := &in.RebindTimer, &out.RebindTimer
		*out = new(int32)
		**out = **in
	}
	if in.Authoritative != nil {
		in, out := &in.Authoritative, &out.Authoritative
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedNetwork4.
func (in *SharedNetwork4) DeepCopy() *SharedNetwork4 {
	if in == nil {
		return nil
	}
	out := new(SharedNetwork4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedNetwork6) DeepCopyInto(out *SharedNetwork6) {
	*out = *in
	if in.Subnet6 != nil {
		in, out := &in.Subnet6, &out.Subnet6
		*out = make([]Subnet6, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Relay != nil {
		in, out := &in.Relay, &out.Relay
		*out = new(RelayInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.PreferredLifetime != nil {
		in, out := &in.PreferredLifetime, &out.PreferredLifetime
		*out = new(int32)
		**out = **in
	}
	if in.ValidLifetime != nil {
		in, out := &in.ValidLifetime, &out.ValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.RenewTimer != nil {
		in, out := &in.RenewTimer, &out.RenewTimer
		*out = new(int32)
		**out = **in
	}
	if in.RebindTimer != nil {
		in, out := &in.RebindTimer, &out.RebindTimer
		*out = new(int32)
		**out = **in
	}
	if in.RapidCommit != nil {
		in, out := &in.RapidCommit, &out.RapidCommit
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedNetwork6.
func (in *SharedNetwork6) DeepCopy() *SharedNetwork6 {
	if in == nil {
		return nil
	}
	out := new(SharedNetwork6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorkAgentConfig) DeepCopyInto(out *StorkAgentConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ServerTokenSecretRef != nil {
		in, out := &in.ServerTokenSecretRef, &out.ServerTokenSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.StorkServerRef != nil {
		in, out := &in.StorkServerRef, &out.StorkServerRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.PrometheusPort != nil {
		in, out := &in.PrometheusPort, &out.PrometheusPort
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorkAgentConfig.
func (in *StorkAgentConfig) DeepCopy() *StorkAgentConfig {
	if in == nil {
		return nil
	}
	out := new(StorkAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorkServerDatabase) DeepCopyInto(out *StorkServerDatabase) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	out.CredentialsSecretRef = in.CredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorkServerDatabase.
func (in *StorkServerDatabase) DeepCopy() *StorkServerDatabase {
	if in == nil {
		return nil
	}
	out := new(StorkServerDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subnet4) DeepCopyInto(out *Subnet4) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]Pool4, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make([]Reservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequireClientClasses != nil {
		in, out := &in.RequireClientClasses, &out.RequireClientClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Relay != nil {
		in, out := &in.Relay, &out.Relay
		*out = new(RelayInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.ValidLifetime != nil {
		in, out := &in.ValidLifetime, &out.ValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MinValidLifetime != nil {
		in, out := &in.MinValidLifetime, &out.MinValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MaxValidLifetime != nil {
		in, out := &in.MaxValidLifetime, &out.MaxValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.RenewTimer != nil {
		in, out := &in.RenewTimer, &out.RenewTimer
		*out = new(int32)
		**out = **in
	}
	if in.RebindTimer != nil {
		in, out := &in.RebindTimer, &out.RebindTimer
		*out = new(int32)
		**out = **in
	}
	if in.Authoritative != nil {
		in, out := &in.Authoritative, &out.Authoritative
		*out = new(bool)
		**out = **in
	}
	if in.MatchClientID != nil {
		in, out := &in.MatchClientID, &out.MatchClientID
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subnet4.
func (in *Subnet4) DeepCopy() *Subnet4 {
	if in == nil {
		return nil
	}
	out := new(Subnet4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subnet6) DeepCopyInto(out *Subnet6) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]Pool6, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PDPools != nil {
		in, out := &in.PDPools, &out.PDPools
		*out = make([]PDPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OptionData != nil {
		in, out := &in.OptionData, &out.OptionData
		*out = make([]OptionData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make([]Reservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequireClientClasses != nil {
		in, out := &in.RequireClientClasses, &out.RequireClientClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Relay != nil {
		in, out := &in.Relay, &out.Relay
		*out = new(RelayInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.PreferredLifetime != nil {
		in, out := &in.PreferredLifetime, &out.PreferredLifetime
		*out = new(int32)
		**out = **in
	}
	if in.ValidLifetime != nil {
		in, out := &in.ValidLifetime, &out.ValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MinValidLifetime != nil {
		in, out := &in.MinValidLifetime, &out.MinValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.MaxValidLifetime != nil {
		in, out := &in.MaxValidLifetime, &out.MaxValidLifetime
		*out = new(int32)
		**out = **in
	}
	if in.RenewTimer != nil {
		in, out := &in.RenewTimer, &out.RenewTimer
		*out = new(int32)
		**out = **in
	}
	if in.RebindTimer != nil {
		in, out := &in.RebindTimer, &out.RebindTimer
		*out = new(int32)
		**out = **in
	}
	if in.RapidCommit != nil {
		in, out := &in.RapidCommit, &out.RapidCommit
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subnet6.
func (in *Subnet6) DeepCopy() *Subnet6 {
	if in == nil {
		return nil
	}
	out := new(Subnet6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.CertRequired != nil {
		in, out := &in.CertRequired, &out.CertRequired
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TSIGKey) DeepCopyInto(out *TSIGKey) {
	*out = *in
	if in.DigestBits != nil {
		in, out := &in.DigestBits, &out.DigestBits
		*out = new(int32)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TSIGKey.
func (in *TSIGKey) DeepCopy() *TSIGKey {
	if in == nil {
		return nil
	}
	out := new(TSIGKey)
	in.DeepCopyInto(out)
	return out
}
