apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: {{ .Values.plugin.name }}
spec:
  displayName: {{ .Values.plugin.displayName | quote }}
  backend:
    type: Service
    service:
      name: {{ .Values.plugin.name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.plugin.port }}
      basePath: "/"
  proxy:
    - alias: backend
      endpoint:
        type: Service
        service:
          name: {{ .Values.plugin.name }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.plugin.backendPort }}
      authorization: UserToken
  i18n:
    loadType: Preload
