apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.plugin.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.plugin.name }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.plugin.name }}-cert
spec:
  selector:
    app: {{ .Values.plugin.name }}
  ports:
    - name: https
      port: {{ .Values.plugin.port }}
      targetPort: 9443
      protocol: TCP
    - name: backend
      port: {{ .Values.plugin.backendPort }}
      targetPort: 9444
      protocol: TCP
